import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import fieldsRouter from "./fields";
import recordingsRouter from "./recordings";
import clipsRouter from "./clips";
import savedClipsRouter from "./savedClips";
import userClipsRouter from "./userClips";
import accountRouter from "./account";
import adsRouter from "./ads";
import adminRouter from "./admin";
import adminSettingsRouter from "./adminSettings";
import clientSettingsRouter from "./clientSettings";
import bannersRouter from "./banners";
import bunnyVideosRouter from "./bunnyVideos";
import bunnyCollectionsRouter from "./bunnyCollections";
import usersRouter from "./users";
import academiesRouter from "./academies";
import contaboRouter from "./contabo";
import liveRouter from "./live";
import hlsProxyRouter from "./hlsProxy";
import liveSchedulesRouter from "./liveSchedules";
import clipIntroRouter from "./clipIntro";
import matchesRouter from "./matches";
import claimMatchRouter from "./claimMatch";
import analysisJobsRouter from "./analysisJobs";
import brandingRouter from "./branding";
import claimOffPitchRouter from "./claimOffPitch";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(bunnyCollectionsRouter);
router.use(bunnyVideosRouter);
router.use(fieldsRouter);
router.use(recordingsRouter);
router.use(clipsRouter);
router.use(savedClipsRouter);
router.use(userClipsRouter);
router.use(accountRouter);
router.use(adsRouter);
router.use(bannersRouter);
router.use(adminRouter);
router.use(adminSettingsRouter);
router.use(clientSettingsRouter);
router.use(usersRouter);
router.use(academiesRouter);
router.use(contaboRouter);
router.use(liveRouter);
router.use(hlsProxyRouter);
router.use(liveSchedulesRouter);
router.use(clipIntroRouter);
router.use(matchesRouter);
router.use(claimMatchRouter);
router.use(analysisJobsRouter);
router.use(brandingRouter);
router.use(claimOffPitchRouter);

export default router;
