import { shadcn } from "@clerk/themes";

const basePath = import.meta.env.BASE_URL.replace(/\/$/, "");

export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: "clerk",
  options: {
    logoPlacement: "inside" as const,
    logoLinkUrl: basePath || "/",
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
  },
  variables: {
    colorPrimary: "#39FF14",
    colorForeground: "hsl(0 0% 96%)",
    colorMutedForeground: "hsl(0 0% 55%)",
    colorDanger: "hsl(348 100% 58%)",
    colorBackground: "hsl(0 0% 7%)",
    colorInput: "hsl(0 0% 14%)",
    colorInputForeground: "hsl(0 0% 96%)",
    colorNeutral: "hsl(0 0% 20%)",
    fontFamily: "'Space Grotesk', sans-serif",
    borderRadius: "0.75rem",
  },
  elements: {
    rootBox: "w-full flex justify-center",
    cardBox: "bg-zinc-900 rounded-2xl w-[440px] max-w-full overflow-hidden shadow-2xl",
    card: "!shadow-none !border-0 !bg-transparent !rounded-none",
    footer: "!shadow-none !border-0 !bg-transparent !rounded-none",
    headerTitle: "text-white font-bold",
    headerSubtitle: "text-zinc-400",
    socialButtonsBlockButtonText: "text-zinc-300 font-medium",
    formFieldLabel: "text-zinc-300 font-medium",
    footerActionLink: "text-[#39FF14] font-semibold",
    footerActionText: "text-zinc-500",
    dividerText: "text-zinc-600",
    identityPreviewEditButton: "text-[#39FF14]",
    formFieldSuccessText: "text-[#39FF14]",
    alertText: "text-zinc-300",
    logoBox: "mb-2",
    logoImage: "h-10 w-10",
    socialButtonsBlockButton: "border-zinc-700 hover:bg-zinc-800",
    formButtonPrimary: "bg-[#39FF14] hover:bg-[#2de012] text-black font-semibold",
    formFieldInput: "border-zinc-700 focus:border-[#39FF14] bg-zinc-800 text-white",
    footerAction: "bg-zinc-900",
    dividerLine: "bg-zinc-700",
    alert: "bg-red-900/30 border-red-800",
    otpCodeFieldInput: "border-zinc-700 focus:border-[#39FF14]",
    formFieldRow: "",
    main: "",
  },
};
